#!/bin/bash

CLASSPATH="cupidoGWT/war/WEB-INF/classes:cupidoBackendImpl/bin:cupidoCommon/bin:cupidoBackendImpl/jargs.jar"

rmic -d cupidoBackendImpl/bin -classpath "$CLASSPATH" 'unibo.as.cupido.backendInterfacesImpl.table.playerUI.RemoteBot'



java -classpath "$CLASSPATH" unibo.as.cupido.backendInterfacesImpl.table.playerUI.PlayerConsoleUI
