#!/bin/bash

CLASSPATH="cupidoGWT/war/WEB-INF/classes:cupidoBackendImpl/bin:cupidoCommon/bin:cupidoBackendImpl/jargs.jar"

java -classpath "$CLASSPATH" unibo.as.cupido.backend.playerUI.PlayerConsoleUI cupidoBackendImpl/test/joinATableAndLeave
