#!/bin/bash

CLASSPATH="cupidoGWT/war/WEB-INF/classes:cupidoBackendImpl/bin:cupidoCommon/bin:cupidoBackendImpl/jargs.jar"

java -classpath "$CLASSPATH" unibo.as.cupido.backend.playerUI.PlayerConsoleUI cupidoBackendImpl/test/createTableAndAddThreeBot 2>&1 \
| {
while read line
do
  echo -n 'A: '
  echo "$line"
done
} &

PID1="$!"

wait "$PID1"

kill -9 "$PID1" &>/dev/null
